DISCLAIMER = (
    "\n\n---\n"
    "Clinical Disclaimer: This output is generated by an AI system and is "
    "not a substitute for professional medical advice, diagnosis, or treatment. "
    "Always seek the advice of a qualified healthcare provider with any questions "
    "regarding a medical condition. In case of emergency, call your local emergency number."
)


def append_disclaimer(content: str, enabled: bool = True) -> str:
    if not enabled:
        return content
    if DISCLAIMER.strip() in content:
        return content
    return content + DISCLAIMER
